### ISSUE TITLE
compile error on msgraph_onedrive.pks

### ISSUE THREAD

**Issue by warrencaples** [cdngmnks/msgraph-sdk-plsql#25]
**Describe the bug**
error when compiling, msgraph_onedrive.pks, saying that in line 178 folder_child_count must be defined.
I think maybe you can fix by replacing v_value in these that line and the following line with v_items(v_items.count) like so:

IF p_recursive = 'Y' AND v_items(v_items.count).folder_child_count > 0 THEN

            v_child_items := list_folder_children ( p_drive_id => p_drive_id, p_parent_item_id => v_items(v_items.count).id, p_include_parent => 'N', p_recursive => 'Y' );

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by warrencaples** [comment]
Wow, that was fast!  Thanks for putting this together, by the way.  I’ve been doing cobbled together pieces of this myself, it’s so great that you built something like this!

Warren Caples | HX5 | Director, Management Information Systems
O: 850.362.6551 | M: 830.743.9467 | ***@***.******@***.***>
212 Eglin Parkway SE | Fort Walton Beach, FL 32548
HXFIVE.COM

NOTICE - This communication may contain confidential and privileged information that is for the sole use of the intended recipient. Any viewing, copying or distribution of, or reliance on this message by unintended recipients is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by pauljereb** [comment]
Glad if it helps, thanks for pointing out the bug!

BR Paul
________________________________
